import Image, { ImageProps } from "next/image";

const defaultPlaceholder =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAAAAAB3tzPbAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElNRQflAQcGOwAS1aISAAABZklEQVR42u3YPUtCURzH8RM9aYu+iybXhtbAoaktvFtzNBSuDRG1C0lDGNQaNfR6ehtB0YO1SudKQvT36uezHoTfV+FePCkBAAAAAAAAAAAAwLxqFbuTKdajJ486fnuezMdB9ORRp8NJHUZPFhA9WUD0ZAHRkwVETxYQPVlA9GQB0ZMFRE8WED15xgLOqh7Qebwvcff0WYWAxZUy6eK9CgFj9AT8mdbxacZ5ZzGlrfPs0U5tqgKKl+yU+5XSp9B1c6oCdp9LA0reA4OGAAECBAgQIECAAAECBAgQMAsBxWt2ysP4P/X9/M3c0cL/B2xcXg9+utlfSmnnZpA72qun1LnKHd22A36B5UZOc+37qNbMHtW/v+Z6/lOrAQFMse1+L6PfqUcP+62T4XvG8KoRPey3xrwHqkFANAHRBEQTEE1ANAHRBEQTEE1AtMoHjLlarIbN7mFGt+3+DQAAAAAAAAAAAIC59QXwniIE0mnBvQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMS0wMS0wN1QwNjo1OTowMCswMTowMKS0RS8AAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjEtMDEtMDdUMDY6NTk6MDArMDE6MDDV6f2TAAAAV3pUWHRSYXcgcHJvZmlsZSB0eXBlIGlwdGMAAHic4/IMCHFWKCjKT8vMSeVSAAMjCy5jCxMjE0uTFAMTIESANMNkAyOzVCDL2NTIxMzEHMQHy4BIoEouAOoXEXTyQjWVAAAAAElFTkSuQmCC";

export function ImageWrapper({ src, alt, height, width }: ImageProps) {
  return (
    <Image
      alt={alt}
      height={height}
      placeholder={defaultPlaceholder}
      src={src || defaultPlaceholder}
      width={width}
    />
  );
}
