name: Repository visualization
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * SUN"

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Update root visualization
        uses: githubocto/repo-visualizer@main
        with:
          commit_message: "chore: update root visualization"
          root_path: "/"
          output_file: "./readme/root-visualization.svg"
          branch: "repo-visualization"
      - name: Update app visualization
        uses: githubocto/repo-visualizer@main
        with:
          commit_message: "chore: update app visualization"
          root_path: "apps/tessellator/"
          output_file: "./apps/tessellator/readme/app-visualization.svg"
      - name: Update api visualization
        uses: githubocto/repo-visualizer@main
        with:
          commit_message: "chore: update api visualization"
          root_path: "apps/api/"
          output_file: "./apps/api/readme/api-visualization.svg"
